// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sistema de Chaves JRS - Gerenciamento de Imóveis",
  description: "Sistema completo para gerenciamento de chaves de imóveis da JRS Imóveis. Controle de retirada, devolução e status das chaves em tempo real.",
  keywords: "sistema chaves, imóveis, JRS, gerenciamento, controle, retirada, devolução",
  authors: [{ name: "JRS Imóveis" }],
  creator: "Lasy AI",
  publisher: "JRS Imóveis",
  robots: "index, follow",
  openGraph: {
    title: "Sistema de Chaves JRS",
    description: "Gerenciamento completo de chaves de imóveis",
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "Sistema de Chaves JRS",
    description: "Gerenciamento completo de chaves de imóveis",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
  themeColor: "#3b82f6",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Sistema Chaves JRS" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}